### ISSUE TITLE
ubuntu镜像md5不对

### ISSUE THREAD

**Issue by paulzhn** [paulzhn/bjtu-mirror-issues#6]
![TIM图片20190508164447](https://user-images.githubusercontent.com/8180364/57362095-9d5fe100-71b0-11e9-88d8-71a152887bdb.png)
如图，中间的是从清华镜像下载的，md5和官方的一致；1、3是从交大镜像用不同的下载工具下载的。猜测这不是偶发情况，可能整个交大镜像的软件包都存在类似问题。

**Comment by AlynxZhou** [comment]
@ideal 学长怎么看？mirror 的上游是清华的源，难道是 rsync 同步时候不检查文件 md5 只检查文件名，然后某次同步出错了就一直没再同步？

**Comment by ideal** [comment]
@AlynxZhou 我试了确实有这个问题。你看下ubuntu-releases的同步日志？

**Comment by ideal** [comment]
ubuntu-releases这个的上游是清华的吗？

**Comment by AlynxZhou** [comment]
@ideal 上游是清华的，而且这个文件最近都没变过，rsync 日志也没问题

**Comment by ideal** [comment]
有点诡异。会不会和之前磁盘出问题有关？

**Comment by ideal** [comment]
https://serverfault.com/questions/211005/rsync-difference-between-checksum-and-ignore-times-options rsync命令有--checksum参数吗？

**Comment by AlynxZhou** [comment]
@ideal `mirror.ini` 里面应该是没有 `--checksum`。诡异的在于它文件大小还是一样的（

**Comment by AlynxZhou** [comment]
我加一下 checksum 吧

**Comment by ideal** [comment]
感觉应该是当时磁盘问题。或者你把两个文件十六进制比较看看。
