### ISSUE TITLE
composer镜像请求

### ISSUE THREAD

**Issue by ideal** [paulzhn/bjtu-mirror-issues#7]
有个邮件发到我之前的邮箱了，转到这里一下。@paulzhn 可以评估一下。谢谢。

`
Hi，
  交大校友你好，我是来自LC（https://laravel-china.org/）社区的，本社区维护了一份 PHP Composer 的国内镜像（https://packagist.laravel-china.org/），目前运行良好，但由于财力问题，面临无法支付高昂带宽费用的窘境，所以想与贵校合作，部署一份国内镜像在贵校的镜像上。我们可以提供镜像的源代码（https://github.com/zencodex/composer-mirror），希望可以得到一些支持。
`

**Comment by paulzhn** [comment]
收到，已经联系上了

**Comment by paulzhn** [comment]
收到，已经联系上了

在 2019年6月24日，下午3:46，Shang Yuanchun <notifications@github.com<mailto:notifications@github.com>> 写道：


有个邮件发到我之前的邮箱了，转到这里一下。@paulzhn<https://github.com/paulzhn> 可以评估一下。谢谢。

Hi， 交大校友你好，我是来自LC（https://laravel-china.org/）社区的，本社区维护了一份 PHP Composer 的国内镜像（https://packagist.laravel-china.org/），目前运行良好，但由于财力问题，面临无法支付高昂带宽费用的窘境，所以想与贵校合作，部署一份国内镜像在贵校的镜像上。我们可以提供镜像的源代码（https://github.com/zencodex/composer-mirror），希望可以得到一些支持。
